document.writeln("<div class='ite_title mt2'>--近期发货记录，没有录入的客户也会正常发货--</div>");
document.writeln("<div class='codiv'><div id=\"qdemo\" style=\"MARGIN: 0px; OVERFLOW: hidden; WIDTH: 100%; HEIGHT: 447px\">");
document.writeln("  <div id=\"qdemo1\">");
document.writeln("<div id=\"fah_list\">");
document.writeln("<script language=\"JavaScript\">");
document.writeln("var i=0;");
document.writeln("for(i=0;i<44;i++){");
document.writeln("tmpDate=new Date();");
document.writeln("date=tmpDate.getDate();");
document.writeln("month= tmpDate.getMonth() + 1 ;");
document.writeln("year= tmpDate.getFullYear();");
document.writeln("document.write(\"<p class='mai_title'>\");");
document.writeln("document.write(year);");
document.writeln("document.write(\"年\");");
document.writeln("document.write(month);");
document.writeln("document.write(\"月\");");
document.writeln("document.write(date);");
document.writeln("document.write(\"日\");");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\' 北京的\' ");
document.writeln("quotes[2]=\' 上海的\' ");
document.writeln("quotes[3]=\' 天津的\' ");
document.writeln("quotes[4]=\' 湖南的\' ");
document.writeln("quotes[5]=\' 湖北的\' ");
document.writeln("quotes[6]=\' 湖北的\' ");
document.writeln("quotes[7]=\' 广东的\' ");
document.writeln("quotes[8]=\' 广西的\' ");
document.writeln("quotes[9]=\' 重庆的\' ");
document.writeln("quotes[10]=\' 四川的\' ");
document.writeln("quotes[11]=\' 山东的\' ");
document.writeln("quotes[12]=\' 河南的\' ");
document.writeln("quotes[13]=\' 河北的\' ");
document.writeln("quotes[14]=\' 山西的\' ");
document.writeln("quotes[15]=\' 贵州的\' ");
document.writeln("quotes[16]=\' 黑龙江的\' ");
document.writeln("quotes[17]=\' 福建的\' ");
document.writeln("quotes[18]=\' 浙江的\' ");
document.writeln("quotes[19]=\' 江苏的\' ");
document.writeln("quotes[20]=\' 江西的\' ");
document.writeln("quotes[21]=\' 海南的\' ");
document.writeln("quotes[22]=\' 陕西的\'");
document.writeln("quotes[23]=\' 北京的\' ");
document.writeln("quotes[24]=\' 上海的\' ");
document.writeln("quotes[25]=\' 天津的\' ");
document.writeln("quotes[26]=\' 湖南的\' ");
document.writeln("quotes[27]=\' 湖北的\' ");
document.writeln("quotes[28]=\' 湖北的\' ");
document.writeln("quotes[29]=\' 广东的\' ");
document.writeln("quotes[30]=\' 广西的\' ");
document.writeln("quotes[31]=\' 重庆的\' ");
document.writeln("quotes[32]=\' 四川的\' ");
document.writeln("quotes[33]=\' 山东的\' ");
document.writeln("quotes[34]=\' 河南的\' ");
document.writeln("quotes[35]=\' 河北的\' ");
document.writeln("quotes[36]=\' 山西的\' ");
document.writeln("quotes[37]=\' 贵州的\' ");
document.writeln("quotes[38]=\' 黑龙江的\' ");
document.writeln("quotes[39]=\' 福建的\' ");
document.writeln("quotes[40]=\' 浙江的\' ");
document.writeln("quotes[41]=\' 江苏的\' ");
document.writeln("quotes[42]=\' 江西的\' ");
document.writeln("quotes[43]=\' 海南的\' ");
document.writeln("quotes[44]=\' 陕西的\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\'张女士\' ");
document.writeln("quotes[2]=\'刘小姐\' ");
document.writeln("quotes[3]=\'周女士\' ");
document.writeln("quotes[4]=\'吴女士\' ");
document.writeln("quotes[5]=\'朱小姐\' ");
document.writeln("quotes[6]=\'陈女士\' ");
document.writeln("quotes[7]=\'田小姐\' ");
document.writeln("quotes[8]=\'钟女士\' ");
document.writeln("quotes[9]=\'马女士\' ");
document.writeln("quotes[10]=\'韩小姐\' ");
document.writeln("quotes[11]=\'顾小姐\' ");
document.writeln("quotes[12]=\'王女士\' ");
document.writeln("quotes[13]=\'李女士\' ");
document.writeln("quotes[14]=\'卢女士\' ");
document.writeln("quotes[15]=\'崔小姐\' ");
document.writeln("quotes[16]=\'段小姐\' ");
document.writeln("quotes[17]=\'胡女士\' ");
document.writeln("quotes[18]=\'潘小姐\' ");
document.writeln("quotes[19]=\'陈小姐\' ");
document.writeln("quotes[20]=\'林女士\' ");
document.writeln("quotes[21]=\'代女士\' ");
document.writeln("quotes[22]=\'文女士\' ");
document.writeln("quotes[23]=\'孟小姐\' ");
document.writeln("quotes[24]=\'辛女士\' ");
document.writeln("quotes[25]=\'师女士\' ");
document.writeln("quotes[26]=\'汪小姐\' ");
document.writeln("quotes[27]=\'吕女士\' ");
document.writeln("quotes[28]=\'何小姐\' ");
document.writeln("quotes[29]=\'许女士\' ");
document.writeln("quotes[30]=\'冯女士\' ");
document.writeln("quotes[31]=\'李小姐\' ");
document.writeln("quotes[32]=\'余小姐\' ");
document.writeln("quotes[33]=\'毛女士\' ");
document.writeln("quotes[34]=\'韩女士\' ");
document.writeln("quotes[35]=\'于女士\' ");
document.writeln("quotes[36]=\'颜小姐\' ");
document.writeln("quotes[37]=\'段小姐\' ");
document.writeln("quotes[38]=\'欧阳女士\' ");
document.writeln("quotes[39]=\'司徒小姐\' ");
document.writeln("quotes[40]=\'阮小姐\' ");
document.writeln("quotes[41]=\'焦女士\' ");
document.writeln("quotes[42]=\'褚女士\' ");
document.writeln("quotes[43]=\'毕女士\'");
document.writeln("quotes[44]=\'苏女士\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1)");
document.writeln("quotes=new Array ");
document.writeln("var j=1;");
document.writeln("for(j=1;j<45;j++){");
document.writeln("var str=\'（*******\' + parseInt(Math.random()*9+1)+ parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+\'）\' ");
document.writeln("quotes[j]=str");
document.writeln("}");
document.writeln("var quote=quotes[rand1] ");
document.writeln("document.write(quote) ");
document.writeln("document.write(\"</p><p class='mai_con'>\");");
document.writeln("var rand1=parseInt(Math.random()*4+1)");
document.writeln("quotes=new Array");
document.writeln("quotes[1]=\'您的订单已经到达当地，请您电话保持开通状态，谢谢！\'");
document.writeln("quotes[2]=\'您的订单已经订购成功，正在处理中！\'");
document.writeln("quotes[3]=\'您的订单已经签收，祝您吉祥如意！\'");
document.writeln("quotes[4]=\'您的订单已经发货，请您注意签收，谢谢!\'");
document.writeln("var quote=quotes[rand1]");
document.writeln("document.write(quote)");
document.writeln("document.write(\"</p>\");");
document.writeln("}");
document.writeln("</script>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div id=\"qdemo2\">");
document.writeln("<div id=\"fah_list\">");
document.writeln("<script language=\"JavaScript\">");
document.writeln("var i=0;");
document.writeln("for(i=0;i<44;i++){");
document.writeln("tmpDate=new Date();");
document.writeln("date=tmpDate.getDate();");
document.writeln("month= tmpDate.getMonth() + 1 ;");
document.writeln("year= tmpDate.getFullYear();");
document.writeln("document.write(\"<p class='mai_title'>\");");
document.writeln("document.write(year);");
document.writeln("document.write(\"年\");");
document.writeln("document.write(month);");
document.writeln("document.write(\"月\");");
document.writeln("document.write(date);");
document.writeln("document.write(\"日\");");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\' 北京的\' ");
document.writeln("quotes[2]=\' 上海的\' ");
document.writeln("quotes[3]=\' 天津的\' ");
document.writeln("quotes[4]=\' 湖南的\' ");
document.writeln("quotes[5]=\' 湖北的\' ");
document.writeln("quotes[6]=\' 湖北的\' ");
document.writeln("quotes[7]=\' 广东的\' ");
document.writeln("quotes[8]=\' 广西的\' ");
document.writeln("quotes[9]=\' 重庆的\' ");
document.writeln("quotes[10]=\' 四川的\' ");
document.writeln("quotes[11]=\' 山东的\' ");
document.writeln("quotes[12]=\' 河南的\' ");
document.writeln("quotes[13]=\' 河北的\' ");
document.writeln("quotes[14]=\' 山西的\' ");
document.writeln("quotes[15]=\' 贵州的\' ");
document.writeln("quotes[16]=\' 黑龙江的\' ");
document.writeln("quotes[17]=\' 福建的\' ");
document.writeln("quotes[18]=\' 浙江的\' ");
document.writeln("quotes[19]=\' 江苏的\' ");
document.writeln("quotes[20]=\' 江西的\' ");
document.writeln("quotes[21]=\' 海南的\' ");
document.writeln("quotes[22]=\' 陕西的\'");
document.writeln("quotes[23]=\' 北京的\' ");
document.writeln("quotes[24]=\' 上海的\' ");
document.writeln("quotes[25]=\' 天津的\' ");
document.writeln("quotes[26]=\' 湖南的\' ");
document.writeln("quotes[27]=\' 湖北的\' ");
document.writeln("quotes[28]=\' 湖北的\' ");
document.writeln("quotes[29]=\' 广东的\' ");
document.writeln("quotes[30]=\' 广西的\' ");
document.writeln("quotes[31]=\' 重庆的\' ");
document.writeln("quotes[32]=\' 四川的\' ");
document.writeln("quotes[33]=\' 山东的\' ");
document.writeln("quotes[34]=\' 河南的\' ");
document.writeln("quotes[35]=\' 河北的\' ");
document.writeln("quotes[36]=\' 山西的\' ");
document.writeln("quotes[37]=\' 贵州的\' ");
document.writeln("quotes[38]=\' 黑龙江的\' ");
document.writeln("quotes[39]=\' 福建的\' ");
document.writeln("quotes[40]=\' 浙江的\' ");
document.writeln("quotes[41]=\' 江苏的\' ");
document.writeln("quotes[42]=\' 江西的\' ");
document.writeln("quotes[43]=\' 海南的\' ");
document.writeln("quotes[44]=\' 陕西的\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\'张女士\' ");
document.writeln("quotes[2]=\'刘小姐\' ");
document.writeln("quotes[3]=\'周女士\' ");
document.writeln("quotes[4]=\'吴女士\' ");
document.writeln("quotes[5]=\'朱小姐\' ");
document.writeln("quotes[6]=\'陈女士\' ");
document.writeln("quotes[7]=\'田小姐\' ");
document.writeln("quotes[8]=\'钟女士\' ");
document.writeln("quotes[9]=\'马女士\' ");
document.writeln("quotes[10]=\'韩小姐\' ");
document.writeln("quotes[11]=\'顾小姐\' ");
document.writeln("quotes[12]=\'王女士\' ");
document.writeln("quotes[13]=\'李女士\' ");
document.writeln("quotes[14]=\'卢女士\' ");
document.writeln("quotes[15]=\'崔小姐\' ");
document.writeln("quotes[16]=\'段小姐\' ");
document.writeln("quotes[17]=\'胡女士\' ");
document.writeln("quotes[18]=\'潘小姐\' ");
document.writeln("quotes[19]=\'陈小姐\' ");
document.writeln("quotes[20]=\'林女士\' ");
document.writeln("quotes[21]=\'代女士\' ");
document.writeln("quotes[22]=\'文女士\' ");
document.writeln("quotes[23]=\'孟小姐\' ");
document.writeln("quotes[24]=\'辛女士\' ");
document.writeln("quotes[25]=\'师女士\' ");
document.writeln("quotes[26]=\'汪小姐\' ");
document.writeln("quotes[27]=\'吕女士\' ");
document.writeln("quotes[28]=\'何小姐\' ");
document.writeln("quotes[29]=\'许女士\' ");
document.writeln("quotes[30]=\'冯女士\' ");
document.writeln("quotes[31]=\'李小姐\' ");
document.writeln("quotes[32]=\'余小姐\' ");
document.writeln("quotes[33]=\'毛女士\' ");
document.writeln("quotes[34]=\'韩女士\' ");
document.writeln("quotes[35]=\'于女士\' ");
document.writeln("quotes[36]=\'颜小姐\' ");
document.writeln("quotes[37]=\'段小姐\' ");
document.writeln("quotes[38]=\'欧阳女士\' ");
document.writeln("quotes[39]=\'司徒小姐\' ");
document.writeln("quotes[40]=\'阮小姐\' ");
document.writeln("quotes[41]=\'焦女士\' ");
document.writeln("quotes[42]=\'褚女士\' ");
document.writeln("quotes[43]=\'毕女士\'");
document.writeln("quotes[44]=\'苏女士\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1)");
document.writeln("quotes=new Array ");
document.writeln("var j=1;");
document.writeln("for(j=1;j<45;j++){");
document.writeln("var str=\'（*******\' + parseInt(Math.random()*9+1)+ parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+\'）\' ");
document.writeln("quotes[j]=str");
document.writeln("}");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("document.write(\"</p><p class='mai_con'>\");");
document.writeln("var rand1=parseInt(Math.random()*4+1)");
document.writeln("//alert(rand1);return false;");
document.writeln("quotes=new Array");
document.writeln("quotes[1]=\'您的订单已经到达当地，请您电话保持开通状态，谢谢！\'");
document.writeln("quotes[2]=\'您的订单已经订购成功，正在处理中！\'");
document.writeln("quotes[3]=\'您的订单已经签收，祝您早日去红血丝成功！\'");
document.writeln("quotes[4]=\'您的订单已经发货，请您注意签收，谢谢!\'");
document.writeln("var quote=quotes[rand1]");
document.writeln("document.write(quote)");
document.writeln("document.write(\"</p>\");");
document.writeln("}");
document.writeln("</script>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div></div>");
document.writeln("<script>");
document.writeln("                        var qspeed=60  ");
document.writeln("                        qdemo2.innerHTML=qdemo1.innerHTML //克隆demo1为demo2  ");
document.writeln("                        function qMarquee(){  ");
document.writeln("                        //当滚动至demo1与demo2交界时  ");
document.writeln("                        if(qdemo2.offsetTop-qdemo.scrollTop<=0)    ");
document.writeln("                        qdemo.scrollTop-=qdemo1.offsetHeight //demo跳到最顶端  ");
document.writeln("                        else{  ");
document.writeln("                        qdemo.scrollTop++  ");
document.writeln("                        }  ");
document.writeln("                        }  ");
document.writeln("                        var qMyMar=setInterval(qMarquee,qspeed)//设置定时器  ");
document.writeln("                        //鼠标移上时清除定时器达到滚动停止的目的  ");
document.writeln("                        qdemo.onmouseover=function() {clearInterval(qMyMar)}  ");
document.writeln("                        //鼠标移开时重设定时器  ");
document.writeln("                        qdemo.onmouseout=function(){qMyMar=setInterval(qMarquee,qspeed)}  ");
document.writeln("                        </script>");