document.writeln("<div class='ite_title mt2'>--购买评论专区--</div>");
document.writeln("<div class='codiv'><DIV id=demo class=comment>");
document.writeln("<DL id=demo1>");
document.writeln("  <DT>镇静 </DT>");
document.writeln("  <DD>效果很好哦，对我帮助很大，解决了我多年的烦恼！ </DD>");
document.writeln("  <DT>林华 </DT>");
document.writeln("  <DD>已经用了一个月的时间，有明显的效果，继续使用中，值得购买！ </DD>");
document.writeln("  <DT>周小姐 </DT>");
document.writeln("  <DD>终于找到这么好的产品，赞一个 </DD>");
document.writeln("  <DT>张女士 </DT>");
document.writeln("  <DD>第二次购买，大家最好直接购买推荐的套餐，一步到位 </DD>");
document.writeln("  <DT>小张 </DT>");
document.writeln("  <DD>打算也给妹妹订一盒，谢谢！ </DD>");
document.writeln("  <DT>王小姐 </DT>");
document.writeln("  <DD>好产品，赞一个！ </DD>");
document.writeln("  <DT>吴女士 </DT>");
document.writeln("  <DD>效果很不错，老教授的产品可真神！！！ </DD>");
document.writeln("  <DT>曹女士 </DT>");
document.writeln("  <DD>果然不错，现在心里石头终于放下去了 </DD>");
document.writeln("  <DT>赵小姐 </DT>");
document.writeln("  <DD>谢谢这么好的产品，让我摆脱了多年的烦恼 </DD>");
document.writeln("  <DT>白女士 </DT>");
document.writeln("  <DD>用了2个月就达到了满意的效果，很不错了 </DD>");
document.writeln("  <DT>丁女士 </DT>");
document.writeln("  <DD>朋友买了一盒使用还行介绍我来购买一盒… </DD>");
document.writeln("  <DT>宇女士 </DT>");
document.writeln("  <DD>和网页宣传一样的好！ </DD>");
document.writeln("  <DT>风一样的女子 </DT>");
document.writeln("  <DD>快递耽误了两天，产品好用 </DD>");
document.writeln("  <DT>小李 </DT>");
document.writeln("  <DD>订购了一盒，和朋友一起用，感觉还行 </DD>");
document.writeln("  <DT>陈女士 </DT>");
document.writeln("  <DD>用了几天感觉效果很不错，期待后续的效果。 </DD>");
document.writeln("  <DT>正女士 </DT>");
document.writeln("  <DD>我用才开始用了一周没有效果，不够后来慢慢效果就开始有了估计是吸收慢 </DD>");
document.writeln("  <DT>郭女士 </DT>");
document.writeln("  <DD>一直想买，找到了就买一盒试试 </DD>");
document.writeln("  <DT>祖玛 </DT>");
document.writeln("  <DD>昨天晚上看到快递的图片，都爆仓了，我昨天也订购一盒。 </DD>");
document.writeln("  <DT>邱女士 </DT>");
document.writeln("  <DD>自己用了一盒效果非常不错，再订一盒今天说没货了，没关系我等。。。 </DD>");
document.writeln("  <DT>傅女士 </DT>");
document.writeln("  <DD>朋友推荐的，刚收到先看看 </DD>");
document.writeln("  <DT>郑女士 </DT>");
document.writeln("  <DD>是表妹推荐使用的，她说之前她用过，效果也不错，跟她一起订购两套， </DD>");
document.writeln("  <DT>博明 </DT>");
document.writeln("  <DD>价格还算实惠吧，期待效果。 </DD>");
document.writeln("  <DT>丽帆 </DT>");
document.writeln("  <DD>多年的烦恼终于解决了很开心 谢谢 </DD>");
document.writeln("  <DT>顾生 </DT>");
document.writeln("  <DD>再便宜一点就更好了哦 </DD></DL>");
document.writeln("<DL id=demo2>");
document.writeln("  <DT>镇静 </DT>");
document.writeln("  <DD>效果很好哦，对我帮助很大，解决了我多年的烦恼！ </DD>");
document.writeln("  <DT>林华 </DT>");
document.writeln("  <DD>已经用了一个月的时间，有明显的效果，继续使用中，值得购买！ </DD>");
document.writeln("  <DT>周小姐 </DT>");
document.writeln("  <DD>终于找到这么好的产品，赞一个 </DD>");
document.writeln("  <DT>张女士 </DT>");
document.writeln("  <DD>第二次购买，大家最好直接购买推荐的套餐，一步到位 </DD>");
document.writeln("  <DT>小张 </DT>");
document.writeln("  <DD>打算也给妹妹订一盒，谢谢！ </DD>");
document.writeln("  <DT>王小姐 </DT>");
document.writeln("  <DD>好产品，赞一个！ </DD>");
document.writeln("  <DT>吴女士 </DT>");
document.writeln("  <DD>效果很不错，老教授的产品可真神！！！ </DD>");
document.writeln("  <DT>曹女士 </DT>");
document.writeln("  <DD>果然不错，现在心里石头终于放下去了 </DD>");
document.writeln("  <DT>赵小姐 </DT>");
document.writeln("  <DD>谢谢这么好的产品，让我摆脱了多年的烦恼 </DD>");
document.writeln("  <DT>白女士 </DT>");
document.writeln("  <DD>用了2个月就达到了满意的效果，很不错了 </DD>");
document.writeln("  <DT>丁女士 </DT>");
document.writeln("  <DD>朋友买了一盒使用还行介绍我来购买一盒… </DD>");
document.writeln("  <DT>宇女士 </DT>");
document.writeln("  <DD>和网页宣传一样的好！ </DD>");
document.writeln("  <DT>风一样的女子 </DT>");
document.writeln("  <DD>快递耽误了两天，产品好用 </DD>");
document.writeln("  <DT>小李 </DT>");
document.writeln("  <DD>订购了一盒，和朋友一起用，感觉还行 </DD>");
document.writeln("  <DT>陈女士 </DT>");
document.writeln("  <DD>用了几天感觉效果很不错，期待后续的效果。 </DD>");
document.writeln("  <DT>正女士 </DT>");
document.writeln("  <DD>我用才开始用了一周没有效果，不够后来慢慢效果就开始有了估计是吸收慢 </DD>");
document.writeln("  <DT>郭女士 </DT>");
document.writeln("  <DD>一直想买，找到了就买一盒试试 </DD>");
document.writeln("  <DT>祖玛 </DT>");
document.writeln("  <DD>昨天晚上看到快递的图片，都爆仓了，我昨天也订购一盒。 </DD>");
document.writeln("  <DT>邱女士 </DT>");
document.writeln("  <DD>自己用了一盒效果非常不错，再订一盒今天说没货了，没关系我等。。。 </DD>");
document.writeln("  <DT>傅女士 </DT>");
document.writeln("  <DD>朋友推荐的，刚收到先看看 </DD>");
document.writeln("  <DT>郑女士 </DT>");
document.writeln("  <DD>是表妹推荐使用的，她说之前她用过，效果也不错，跟她一起订购两套， </DD>");
document.writeln("  <DT>博明 </DT>");
document.writeln("  <DD>价格还算实惠吧，期待效果。 </DD>");
document.writeln("  <DT>丽帆 </DT>");
document.writeln("  <DD>多年的烦恼终于解决了很开心 谢谢 </DD>");
document.writeln("  <DT>顾生 </DT>");
document.writeln("  <DD>再便宜一点就更好了哦 </DD></DL>");
document.writeln("<SCRIPT language=javascript type=text/javascript> ");
document.writeln("// JavaScript Document");
document.writeln("var speed=360;");
document.writeln("var FGDemo=document.getElementById(\'demo\');");
document.writeln("var FGDemo1=document.getElementById(\'demo1\');");
document.writeln("var FGDemo2=document.getElementById(\'demo2\');");
document.writeln("FGDemo2.innerHTML=FGDemo1.innerHTML");
document.writeln("function Marquee1(){");
document.writeln("if(FGDemo2.offsetHeight-FGDemo.scrollTop<=0)");
document.writeln("FGDemo.scrollTop-=FGDemo1.offsetHeight");
document.writeln("else{");
document.writeln("FGDemo.scrollTop++");
document.writeln("}");
document.writeln("}");
document.writeln("var MyMar1=setInterval(Marquee1,speed)");
document.writeln("FGDemo.onmouseover=function() {clearInterval(MyMar1)}");
document.writeln("FGDemo.onmouseout=function() {MyMar1=setInterval(Marquee1,speed)} ");
document.writeln("</SCRIPT>");
document.writeln("</DIV></DIV><div class='codiv codiva mt2'>");
document.writeln("<div class='form_title'><span class='xin_ren'>*</span>昵称：</div><p><input type=\"text\"class=\"mobiletx\"id=\"name\"name=\"username\"value=\"\"/></p><div class='form_title'><span class='xin_ren'>*</span>手机：</div><p><input type=\"text\"class=\"mobiletx\"id=\"mobile\"name=\"mob\"value=\"\"/></p><div class='form_title'><span class='xin_ren'>*</span>评论内容：</div><p><textarea class=\"mobiletextarea\"id=\"Remark\"name=\"beizhu\"></textarea></p><div class=\"ordersumbit f_main\" onclick=\"alert(\'评论提交成功\');\">提交评论</div></div>");
document.writeln("<div class='ite_title mt2'>--近期发货记录，没有录入的客户也会正常发货--</div>");
document.writeln("<div class='codiv'><div id=\"qdemo\" style=\"MARGIN: 0px; OVERFLOW: hidden; WIDTH: 100%; HEIGHT: 447px\">");
document.writeln("  <div id=\"qdemo1\">");
document.writeln("<div id=\"fah_list\">");
document.writeln("<script language=\"JavaScript\">");
document.writeln("var i=0;");
document.writeln("for(i=0;i<44;i++){");
document.writeln("tmpDate=new Date();");
document.writeln("date=tmpDate.getDate();");
document.writeln("month= tmpDate.getMonth() + 1 ;");
document.writeln("year= tmpDate.getFullYear();");
document.writeln("document.write(\"<p class='mai_title'>\");");
document.writeln("document.write(year);");
document.writeln("document.write(\"年\");");
document.writeln("document.write(month);");
document.writeln("document.write(\"月\");");
document.writeln("document.write(date);");
document.writeln("document.write(\"日\");");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\' 北京的\' ");
document.writeln("quotes[2]=\' 上海的\' ");
document.writeln("quotes[3]=\' 天津的\' ");
document.writeln("quotes[4]=\' 湖南的\' ");
document.writeln("quotes[5]=\' 湖北的\' ");
document.writeln("quotes[6]=\' 湖北的\' ");
document.writeln("quotes[7]=\' 广东的\' ");
document.writeln("quotes[8]=\' 广西的\' ");
document.writeln("quotes[9]=\' 重庆的\' ");
document.writeln("quotes[10]=\' 四川的\' ");
document.writeln("quotes[11]=\' 山东的\' ");
document.writeln("quotes[12]=\' 河南的\' ");
document.writeln("quotes[13]=\' 河北的\' ");
document.writeln("quotes[14]=\' 山西的\' ");
document.writeln("quotes[15]=\' 贵州的\' ");
document.writeln("quotes[16]=\' 黑龙江的\' ");
document.writeln("quotes[17]=\' 福建的\' ");
document.writeln("quotes[18]=\' 浙江的\' ");
document.writeln("quotes[19]=\' 江苏的\' ");
document.writeln("quotes[20]=\' 江西的\' ");
document.writeln("quotes[21]=\' 海南的\' ");
document.writeln("quotes[22]=\' 陕西的\'");
document.writeln("quotes[23]=\' 北京的\' ");
document.writeln("quotes[24]=\' 上海的\' ");
document.writeln("quotes[25]=\' 天津的\' ");
document.writeln("quotes[26]=\' 湖南的\' ");
document.writeln("quotes[27]=\' 湖北的\' ");
document.writeln("quotes[28]=\' 湖北的\' ");
document.writeln("quotes[29]=\' 广东的\' ");
document.writeln("quotes[30]=\' 广西的\' ");
document.writeln("quotes[31]=\' 重庆的\' ");
document.writeln("quotes[32]=\' 四川的\' ");
document.writeln("quotes[33]=\' 山东的\' ");
document.writeln("quotes[34]=\' 河南的\' ");
document.writeln("quotes[35]=\' 河北的\' ");
document.writeln("quotes[36]=\' 山西的\' ");
document.writeln("quotes[37]=\' 贵州的\' ");
document.writeln("quotes[38]=\' 黑龙江的\' ");
document.writeln("quotes[39]=\' 福建的\' ");
document.writeln("quotes[40]=\' 浙江的\' ");
document.writeln("quotes[41]=\' 江苏的\' ");
document.writeln("quotes[42]=\' 江西的\' ");
document.writeln("quotes[43]=\' 海南的\' ");
document.writeln("quotes[44]=\' 陕西的\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\'张女士\' ");
document.writeln("quotes[2]=\'刘小姐\' ");
document.writeln("quotes[3]=\'周女士\' ");
document.writeln("quotes[4]=\'吴女士\' ");
document.writeln("quotes[5]=\'朱小姐\' ");
document.writeln("quotes[6]=\'陈女士\' ");
document.writeln("quotes[7]=\'田小姐\' ");
document.writeln("quotes[8]=\'钟女士\' ");
document.writeln("quotes[9]=\'马女士\' ");
document.writeln("quotes[10]=\'韩小姐\' ");
document.writeln("quotes[11]=\'顾小姐\' ");
document.writeln("quotes[12]=\'王女士\' ");
document.writeln("quotes[13]=\'李女士\' ");
document.writeln("quotes[14]=\'卢女士\' ");
document.writeln("quotes[15]=\'崔小姐\' ");
document.writeln("quotes[16]=\'段小姐\' ");
document.writeln("quotes[17]=\'胡女士\' ");
document.writeln("quotes[18]=\'潘小姐\' ");
document.writeln("quotes[19]=\'陈小姐\' ");
document.writeln("quotes[20]=\'林女士\' ");
document.writeln("quotes[21]=\'代女士\' ");
document.writeln("quotes[22]=\'文女士\' ");
document.writeln("quotes[23]=\'孟小姐\' ");
document.writeln("quotes[24]=\'辛女士\' ");
document.writeln("quotes[25]=\'师女士\' ");
document.writeln("quotes[26]=\'汪小姐\' ");
document.writeln("quotes[27]=\'吕女士\' ");
document.writeln("quotes[28]=\'何小姐\' ");
document.writeln("quotes[29]=\'许女士\' ");
document.writeln("quotes[30]=\'冯女士\' ");
document.writeln("quotes[31]=\'李小姐\' ");
document.writeln("quotes[32]=\'余小姐\' ");
document.writeln("quotes[33]=\'毛女士\' ");
document.writeln("quotes[34]=\'韩女士\' ");
document.writeln("quotes[35]=\'于女士\' ");
document.writeln("quotes[36]=\'颜小姐\' ");
document.writeln("quotes[37]=\'段小姐\' ");
document.writeln("quotes[38]=\'欧阳女士\' ");
document.writeln("quotes[39]=\'司徒小姐\' ");
document.writeln("quotes[40]=\'阮小姐\' ");
document.writeln("quotes[41]=\'焦女士\' ");
document.writeln("quotes[42]=\'褚女士\' ");
document.writeln("quotes[43]=\'毕女士\'");
document.writeln("quotes[44]=\'苏女士\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1)");
document.writeln("quotes=new Array ");
document.writeln("var j=1;");
document.writeln("for(j=1;j<45;j++){");
document.writeln("var str=\'（*******\' + parseInt(Math.random()*9+1)+ parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+\'）\' ");
document.writeln("quotes[j]=str");
document.writeln("}");
document.writeln("var quote=quotes[rand1] ");
document.writeln("document.write(quote) ");
document.writeln("document.write(\"</p><p class='mai_con'>\");");
document.writeln("var rand1=parseInt(Math.random()*4+1)");
document.writeln("quotes=new Array");
document.writeln("quotes[1]=\'您的订单已经到达当地，请您电话保持开通状态，谢谢！\'");
document.writeln("quotes[2]=\'您的订单已经订购成功，正在处理中！\'");
document.writeln("quotes[3]=\'您的订单已经签收，祝您吉祥如意！\'");
document.writeln("quotes[4]=\'您的订单已经发货，请您注意签收，谢谢!\'");
document.writeln("var quote=quotes[rand1]");
document.writeln("document.write(quote)");
document.writeln("document.write(\"</p>\");");
document.writeln("}");
document.writeln("</script>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div id=\"qdemo2\">");
document.writeln("<div id=\"fah_list\">");
document.writeln("<script language=\"JavaScript\">");
document.writeln("var i=0;");
document.writeln("for(i=0;i<44;i++){");
document.writeln("tmpDate=new Date();");
document.writeln("date=tmpDate.getDate();");
document.writeln("month= tmpDate.getMonth() + 1 ;");
document.writeln("year= tmpDate.getFullYear();");
document.writeln("document.write(\"<p class='mai_title'>\");");
document.writeln("document.write(year);");
document.writeln("document.write(\"年\");");
document.writeln("document.write(month);");
document.writeln("document.write(\"月\");");
document.writeln("document.write(date);");
document.writeln("document.write(\"日\");");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\' 北京的\' ");
document.writeln("quotes[2]=\' 上海的\' ");
document.writeln("quotes[3]=\' 天津的\' ");
document.writeln("quotes[4]=\' 湖南的\' ");
document.writeln("quotes[5]=\' 湖北的\' ");
document.writeln("quotes[6]=\' 湖北的\' ");
document.writeln("quotes[7]=\' 广东的\' ");
document.writeln("quotes[8]=\' 广西的\' ");
document.writeln("quotes[9]=\' 重庆的\' ");
document.writeln("quotes[10]=\' 四川的\' ");
document.writeln("quotes[11]=\' 山东的\' ");
document.writeln("quotes[12]=\' 河南的\' ");
document.writeln("quotes[13]=\' 河北的\' ");
document.writeln("quotes[14]=\' 山西的\' ");
document.writeln("quotes[15]=\' 贵州的\' ");
document.writeln("quotes[16]=\' 黑龙江的\' ");
document.writeln("quotes[17]=\' 福建的\' ");
document.writeln("quotes[18]=\' 浙江的\' ");
document.writeln("quotes[19]=\' 江苏的\' ");
document.writeln("quotes[20]=\' 江西的\' ");
document.writeln("quotes[21]=\' 海南的\' ");
document.writeln("quotes[22]=\' 陕西的\'");
document.writeln("quotes[23]=\' 北京的\' ");
document.writeln("quotes[24]=\' 上海的\' ");
document.writeln("quotes[25]=\' 天津的\' ");
document.writeln("quotes[26]=\' 湖南的\' ");
document.writeln("quotes[27]=\' 湖北的\' ");
document.writeln("quotes[28]=\' 湖北的\' ");
document.writeln("quotes[29]=\' 广东的\' ");
document.writeln("quotes[30]=\' 广西的\' ");
document.writeln("quotes[31]=\' 重庆的\' ");
document.writeln("quotes[32]=\' 四川的\' ");
document.writeln("quotes[33]=\' 山东的\' ");
document.writeln("quotes[34]=\' 河南的\' ");
document.writeln("quotes[35]=\' 河北的\' ");
document.writeln("quotes[36]=\' 山西的\' ");
document.writeln("quotes[37]=\' 贵州的\' ");
document.writeln("quotes[38]=\' 黑龙江的\' ");
document.writeln("quotes[39]=\' 福建的\' ");
document.writeln("quotes[40]=\' 浙江的\' ");
document.writeln("quotes[41]=\' 江苏的\' ");
document.writeln("quotes[42]=\' 江西的\' ");
document.writeln("quotes[43]=\' 海南的\' ");
document.writeln("quotes[44]=\' 陕西的\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1);");
document.writeln("quotes=new Array ");
document.writeln("quotes[1]=\'张女士\' ");
document.writeln("quotes[2]=\'刘小姐\' ");
document.writeln("quotes[3]=\'周女士\' ");
document.writeln("quotes[4]=\'吴女士\' ");
document.writeln("quotes[5]=\'朱小姐\' ");
document.writeln("quotes[6]=\'陈女士\' ");
document.writeln("quotes[7]=\'田小姐\' ");
document.writeln("quotes[8]=\'钟女士\' ");
document.writeln("quotes[9]=\'马女士\' ");
document.writeln("quotes[10]=\'韩小姐\' ");
document.writeln("quotes[11]=\'顾小姐\' ");
document.writeln("quotes[12]=\'王女士\' ");
document.writeln("quotes[13]=\'李女士\' ");
document.writeln("quotes[14]=\'卢女士\' ");
document.writeln("quotes[15]=\'崔小姐\' ");
document.writeln("quotes[16]=\'段小姐\' ");
document.writeln("quotes[17]=\'胡女士\' ");
document.writeln("quotes[18]=\'潘小姐\' ");
document.writeln("quotes[19]=\'陈小姐\' ");
document.writeln("quotes[20]=\'林女士\' ");
document.writeln("quotes[21]=\'代女士\' ");
document.writeln("quotes[22]=\'文女士\' ");
document.writeln("quotes[23]=\'孟小姐\' ");
document.writeln("quotes[24]=\'辛女士\' ");
document.writeln("quotes[25]=\'师女士\' ");
document.writeln("quotes[26]=\'汪小姐\' ");
document.writeln("quotes[27]=\'吕女士\' ");
document.writeln("quotes[28]=\'何小姐\' ");
document.writeln("quotes[29]=\'许女士\' ");
document.writeln("quotes[30]=\'冯女士\' ");
document.writeln("quotes[31]=\'李小姐\' ");
document.writeln("quotes[32]=\'余小姐\' ");
document.writeln("quotes[33]=\'毛女士\' ");
document.writeln("quotes[34]=\'韩女士\' ");
document.writeln("quotes[35]=\'于女士\' ");
document.writeln("quotes[36]=\'颜小姐\' ");
document.writeln("quotes[37]=\'段小姐\' ");
document.writeln("quotes[38]=\'欧阳女士\' ");
document.writeln("quotes[39]=\'司徒小姐\' ");
document.writeln("quotes[40]=\'阮小姐\' ");
document.writeln("quotes[41]=\'焦女士\' ");
document.writeln("quotes[42]=\'褚女士\' ");
document.writeln("quotes[43]=\'毕女士\'");
document.writeln("quotes[44]=\'苏女士\'");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("");
document.writeln("var rand1=parseInt(Math.random()*44+1)");
document.writeln("quotes=new Array ");
document.writeln("var j=1;");
document.writeln("for(j=1;j<45;j++){");
document.writeln("var str=\'（*******\' + parseInt(Math.random()*9+1)+ parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+parseInt(Math.random()*9+1)+\'）\' ");
document.writeln("quotes[j]=str");
document.writeln("}");
document.writeln("var quote=quotes[rand1] ");
document.writeln("");
document.writeln("document.write(quote) ");
document.writeln("document.write(\"</p><p class='mai_con'>\");");
document.writeln("var rand1=parseInt(Math.random()*4+1)");
document.writeln("//alert(rand1);return false;");
document.writeln("quotes=new Array");
document.writeln("quotes[1]=\'您的订单已经到达当地，请您电话保持开通状态，谢谢！\'");
document.writeln("quotes[2]=\'您的订单已经订购成功，正在处理中！\'");
document.writeln("quotes[3]=\'您的订单已经签收，祝您早日去红血丝成功！\'");
document.writeln("quotes[4]=\'您的订单已经发货，请您注意签收，谢谢!\'");
document.writeln("var quote=quotes[rand1]");
document.writeln("document.write(quote)");
document.writeln("document.write(\"</p>\");");
document.writeln("}");
document.writeln("</script>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div></div>");
document.writeln("<script>");
document.writeln("                        var qspeed=60  ");
document.writeln("                        qdemo2.innerHTML=qdemo1.innerHTML //克隆demo1为demo2  ");
document.writeln("                        function qMarquee(){  ");
document.writeln("                        //当滚动至demo1与demo2交界时  ");
document.writeln("                        if(qdemo2.offsetTop-qdemo.scrollTop<=0)    ");
document.writeln("                        qdemo.scrollTop-=qdemo1.offsetHeight //demo跳到最顶端  ");
document.writeln("                        else{  ");
document.writeln("                        qdemo.scrollTop++  ");
document.writeln("                        }  ");
document.writeln("                        }  ");
document.writeln("                        var qMyMar=setInterval(qMarquee,qspeed)//设置定时器  ");
document.writeln("                        //鼠标移上时清除定时器达到滚动停止的目的  ");
document.writeln("                        qdemo.onmouseover=function() {clearInterval(qMyMar)}  ");
document.writeln("                        //鼠标移开时重设定时器  ");
document.writeln("                        qdemo.onmouseout=function(){qMyMar=setInterval(qMarquee,qspeed)}  ");
document.writeln("                        </script>");